name: Armin Kohlberger Fitness
favicon: null
layout_spectrum: 0.40683538326993585
typography_spectrum: 0.02880702679976821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2540557482279837
  lightness: 0.14636032609269023
  saturation: 0.2704118287656456
  rhythmicContrast: 0.0782938003540039
purpose: []
